### ISSUE TITLE
Algorithm source/paper?

### ISSUE THREAD

**Issue by jubayer-hasan** [despawnerer/summarize#1]
The link you provided ( http://engineering.flipboard.com/2014/10/summarization/ ) is not working. Can you give reference to any research paper for your approach?

**Comment by despawnerer** [comment]
Thanks for letting me know the link is broken. Seems that it has disappeared only recently. The content is still available through web archive: https://web.archive.org/web/20170825024342/http://engineering.flipboard.com/2014/10/summarization/

According to the post, the approach was described by Günes Erkan and collaborators in their 2004 paper "LexRank: Graph-based Lexical Centrality as Salience in Text Summarization" (https://dl.acm.org/citation.cfm?id=1622501), but I have not consulted it when developing this and so cannot directly credit it.

**Comment by despawnerer** [comment]
I've updated the link in README to point to the archived version. Let me know if there's any more information you want.

**Comment by jubayer-hasan** [comment]
Thank you very much. Your approach seemed very informative and helpful to
me. But is there any way to generate without taking a fixed amount of
sentences (like you used to have 5 sentences in your code) as parameter?
Like no fixed number of outputs but it will depend upon the given text?
Thank you again for your help.

**Comment by despawnerer** [comment]
@jubayer-hasan Technically speaking, I don't think anything is stopping us from doing that.

The core result of the algorithm consists of pagerank of each sentence. One could set up a threshold and discard all of the sentences that are below it. I'm not sure how well that would function, but implementation-wise I would make `sentence_count` accept `None` to mean "don't discard any sentences", and add an optional `pagerank_threshold` argument that would be used to specify the minimum pagerank a sentence needs to be kept. Maybe also add some sort of a warning if both `sentence_count` and `pagerank_threshold` are `None` (that would just reorder all of the sentences in order of "importance").

A contribution in the form of a PR would be most welcome :)

**Comment by despawnerer** [comment]
Closing this since the original question was answered
